### ISSUE TITLE
catkin_make命令失效

### ISSUE THREAD

**Issue by HuangCongQing** [HuangCongQing/ROS#16]
修改代码，执行`catkin_make`命令后，结果没任何变化
没有任何报错提示，就是没有编译功能包，心态有点炸啊啊

**Comment by HuangCongQing** [comment]
**暂时解决方法：先删除根目录下的/devel，/build文件夹，再使用catkin_make**
可能原因：我的版本是melodic，和之前版本部分不兼容

**Comment by groers** [comment]
谢谢老哥，我也遇到了这个问题
