### ISSUE TITLE
E: Unable to locate package ros-kinetic-desktop-full

### ISSUE THREAD

**Issue by HuangCongQing** [HuangCongQing/ROS#2]
![image](https://user-images.githubusercontent.com/20675770/56850761-4ef14d80-6939-11e9-9953-afb4813eaacb.png)

**Comment by HuangCongQing** [comment]
https://answers.ros.org/question/278343/unable-to-locate-package-ros-kinetic-desktop-full/

是ROS的版本不对应导致的，每个不同的ubuntu系统对应着不同的ROS版本，如果装错了就会出现上述问题

我是用这个命令解决的
`sudo apt-get install ros-desktop-full`

**Comment by gxnualbert** [comment]
厉害了。我用sudo apt-get install ros-desktop-full也解决了。
![image](https://user-images.githubusercontent.com/15081449/67212063-4f812180-f44e-11e9-90b6-e0843a032fe2.png)

**Comment by tao1587** [comment]
https://stackoverflow.com/questions/61554960/how-to-setup-ros-environment-variable-on-ubuntu-20-04

> The Debian packages are fully functional, but they do not install to /opt/ros. Instead, everything is integrated in the operating system itself. This means that you need to set up your personal workspace slightly differently.
如果用sudo apt-get install ros-desktop-full这个命令就会有问题
